### ISSUE TITLE
looking forward to very much

### ISSUE THREAD

**Issue by Chenxwi** [manjavacas/melkit#1]
when can it be finished？
I very urgently need the tool to extract MELCOR .GEN files

**Comment by manjavacas** [comment]
Hi @Chenxwi,

Although the tool is currently under development, there are already functionalities that can be used. 

These are:

- Reading Control Volumes (`CVs`) and Flow Paths (`FLs`) and converting them to objects.
- Writing, deleting and editing `CVs` and `FLs`.
- Plotting files generated by the `EDF` package.
- Extraction of final values for variables monitored by EDF.
- Obtaining the list of available/used IDs for certain objects (`CVs`, `FLs`).
- Remove all comments from an input file.
- Search for objects by their ID.
- Search for duplicate objects in a given list.

You simply need to instantiate a `Toolkit` with the name of the MELGEN file to manipulate and call those functions. For example:

```
toolkit = Toolkit(filename)
cvs = toolkit.read_cvs()
```

I recommend writing your code in the `run_melkit.py` script, but feel free to use the tool as you wish.

Furthermore, if you have any suggestions and you wish to collaborate in the project, please do so through **Issues** and **Pull requests**. If it is of interest, I could restructure the project and undertake a more "formal" development. 

Any help is welcome! :-)
