### ISSUE TITLE
[FEATURE] Include PTF/EDF handling methods for data visualization

### ISSUE THREAD

**Issue by manjavacas** [manjavacas/melkit#4]
In order to facilitate the manipulation of simulation results 📈 , it is proposed to implement methods aimed at:

- [ ] Visualize data in a similar way to external programs such as _AptPlot_, allowing a more flexible and automated configuration.
- [ ] Automatic generation of plots, reports, etc.
- [ ] Extraction, summary and visualization of different stats.

**Comment by rzehumat** [comment]
Initial ideas in #7

**Comment by manjavacas** [comment]
Hi @rzehumat, any advances on this issue?

**Comment by rzehumat** [comment]
Hi @manjavacas , thanks for the notification. 
I've begun working on it, but then I got into trouble with school and work, so this was postponed. 

If it's ok for you, I'll implement some basic functionality ASAP, while something more "sophisticated" will follow not sure when. 

Also, I've met the developer of meltools. He discontinued it and mentioned that he'll be happy if I reuse any of his ideas here.

**Comment by manjavacas** [comment]
No problem, take as much time as you need. I just wanted to know whether or not this issue had been addressed.

Thanks for the information on `meltools`. Any legacy code that adapts to the `melkit` API will be welcome.

Best regards!

**Comment by rzehumat** [comment]
Ok, so far there is 
- plotting of set of values from 1 file,
- comparison of more PTF files.

Not sure about how AptPlot works. Feel free to suggest features to implement.
