### ISSUE TITLE
Possibly duplicit projects

### ISSUE THREAD

**Issue by rzehumat** [manjavacas/melkit#8]
Hi, 

note: this is not meant to be any discouragement from the project -- I'm rather wondering how to do stuff efficiently.

I was wondering what is worth inventing VS. what is worth taking from somewhere else VS. what is not worth inventing at all. 
In particular, how to avoid [the famous 14 competing standards issue](https://xkcd.com/927/), since there are many similar projects around
- this one,
- https://github.com/petrvokac/meltools,
- https://github.com/dogiv/MelAuto,
- (who knows whatever else).

Although some of them seems discontinued... 
Any thoughts about that? Not sure if you're actually implementing something similar to these or something completely different (I did not dig into the code that much yet...).

**Comment by manjavacas** [comment]
Just to mention, for some basic usage examples and API documentation (with info about all the tools implemented in `MELKIT`), please check https://melkit.readthedocs.io/en/latest/

A more detailed documentation will come as soon as I have more availability.

**Comment by rzehumat** [comment]
Ok, your explanation is reasonable, thanks. I think I will help as well (just not very actively since I have it just as free time project) -- if more issues appear, I can check that. 

> Regarding `meltools`, its last update was 2 years ago. Since it seemed a bit closer to what I expect from MELKIT, I gave it a try, but the fact that it is based on bash and has no documentation made it hard to work with and didn't meet my expectations.

Actually, I think it can be good source of inspiration or help. It's not just bash -- the developer has just hidden everything in the zipped files (e.g. python code is in [meltoolspython-170905.tar.gz](https://github.com/petrvokac/meltools/blob/master/meltoolspython-170905.tar.gz)) -- not sure why, but it's there. If I saw correctly, there are parts in Python, Fortran and Bash.

> If this project came to the attention of the maintainers of meltools or MelAuto I would be happy to hear about their ideas and see if they would be willing to collaborate.

Ok, good point.
